apiVersion: 1
datasources:
  - name: influxdb
    type: influxdb
    access: proxy
    database: sensors
    user: ""
    password: ""
    url: http://influxdb:8086
    basicAuth: true
    editable: true
    isDefault: true
    jsonData:
      version: Flux
      organization: ARCO
      defaultBucket: sensors
    secureJsonData:
      token: "$DOCKER_INFLUXDB_INIT_ADMIN_TOKEN"
      password: admin1234

 